language: python
python:
  - "2.7"

# install dependencies
install: "pip install -r requirements.txt --use-mirrors"

# set up environment variables
env:
  global:
    - ES_VER=1.0.0.RC2
    - ES_MAPPER_ATTACHMENTS_VER=2.0.0.RC1
    - ES_TRANSPORT_THRIFT_VER=2.0.0.RC1
    - ES_RABBITMQ_PLUGIN_VER=2.0.0.RC1

# install Elasticsearch
before_script:
  - ./tests/bin/run_elasticsearch.sh

# run tests
script: nosetests